spring:
  datasource:
    username: root
    url: jdbc:mariadb://localhost:3306/orders?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    password: 'root'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: 'update'
    open-in-view: false 